---
apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: dockercloud/hello-world
        env:
        - name: LISTEN_PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: user
  labels:
    name: user
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - name: user
        image: dockercloud/hello-world
        env:
        - name: LISTEN_PORT
          value: "8000"
        ports:
        - containerPort: 8000
---
apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: mysql
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 6379
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: something-password
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: ""
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: something-password
