---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootPassword: c29tZS1wYXNzd29yZAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  rootPassword: c29tZS1wYXNzd29yZAo=
