---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    env: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: kube-prompt
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
spec:
  selector:
    name: user
  ports:
  - port: 8000
    nodePort: 30100
    protocol: TCP
    name: user
  selector:
    name: kube-prompt
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  selector:
    name: redis
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    name: kube-prompt
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  selector:
    name: mysql
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    name: kube-prompt
  type: ClusterIP
